config/routes.rb
GojoProto::Application.routes.draw do
  resources :users

  resources :entried_positions

  resources :entry_images

  resources :recipes

  resources :entries

  root "home#index"

  resource :usage, controller: :usage

end

app/models/entry_image.rb
class EntryImage < ActiveRecord::Base
  belongs_to :entry
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/entry_images_controller.rb
class EntryImagesController < ApplicationController
  before_action :set_entry_image, only: [:show, :edit, :update, :destroy]

  # GET /entry_images
  # GET /entry_images.json
  def index
    @entry_images = EntryImage.all
  end

  # GET /entry_images/1
  # GET /entry_images/1.json
  def show
  end

  # GET /entry_images/new
  def new
    @entry_image = EntryImage.new
  end

  # GET /entry_images/1/edit
  def edit
  end

  # POST /entry_images
  # POST /entry_images.json
  def create
    @entry_image = EntryImage.new(entry_image_params)

    respond_to do |format|
      if @entry_image.save
        format.html { redirect_to @entry_image, notice: 'Entry image was successfully created.' }
        format.json { render action: 'show', status: :created, location: @entry_image }
      else
        format.html { render action: 'new' }
        format.json { render json: @entry_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entry_images/1
  # PATCH/PUT /entry_images/1.json
  def update
    respond_to do |format|
      if @entry_image.update(entry_image_params)
        format.html { redirect_to @entry_image, notice: 'Entry image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @entry_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entry_images/1
  # DELETE /entry_images/1.json
  def destroy
    @entry_image.destroy
    respond_to do |format|
      format.html { redirect_to entry_images_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry_image
      @entry_image = EntryImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_image_params
      params.require(:entry_image).permit(:entry_id, :text)
    end
end

app/helpers/entry_images_helper.rb
module EntryImagesHelper
end

app/views/entry_images/_form.html.erb
<%= form_for(@entry_image) do |f| %>
  <% if @entry_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry_image.errors.count, "error") %> prohibited this entry_image from being saved:</h2>

      <ul>
      <% @entry_image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :entry_id %><br>
    <%= f.text_field :entry_id %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entry_images/edit.html.erb
<h1>Editing entry_image</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry_image %> |
<%= link_to 'Back', entry_images_path %>

app/views/entry_images/index.html.erb
<h1>Listing entry_images</h1>

<table>
  <thead>
    <tr>
      <th>Entry</th>
      <th>Text</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @entry_images.each do |entry_image| %>
      <tr>
        <td><%= entry_image.entry %></td>
        <td><%= entry_image.text %></td>
        <td><%= link_to 'Show', entry_image %></td>
        <td><%= link_to 'Edit', edit_entry_image_path(entry_image) %></td>
        <td><%= link_to 'Destroy', entry_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entry image', new_entry_image_path %>

app/views/entry_images/new.html.erb
<h1>New entry_image</h1>

<%= render 'form' %>

<%= link_to 'Back', entry_images_path %>

app/views/entry_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Entry:</strong>
  <%= @entry_image.entry %>
</p>

<p>
  <strong>Text:</strong>
  <%= @entry_image.text %>
</p>

<%= link_to 'Edit', edit_entry_image_path(@entry_image) %> |
<%= link_to 'Back', entry_images_path %>